"""
Reason code registry.
Every risk rejection, data block, strategy reject, and execution error
uses a code from this registry. No magic strings anywhere else.
"""

# ── Data quality ──────────────────────────────────────────────────────────────
DATA_STALE = "DATA_STALE"
DATA_GAP_DETECTED = "DATA_GAP_DETECTED"
DATA_SEQUENCE_SKIP = "DATA_SEQUENCE_SKIP"
DATA_DUPLICATE_EVENT = "DATA_DUPLICATE_EVENT"
DATA_MISSING_FEATURE = "DATA_MISSING_FEATURE"
DATA_NON_FINAL_CANDLE = "DATA_NON_FINAL_CANDLE"
DATA_BACKFILL_INCOMPLETE = "DATA_BACKFILL_INCOMPLETE"

# ── Signal / strategy rejects ─────────────────────────────────────────────────
SIGNAL_NO_INVALIDATION_PRICE = "SIGNAL_NO_INVALIDATION_PRICE"
SIGNAL_EXPIRED = "SIGNAL_EXPIRED"
SIGNAL_REGIME_BLOCKED = "SIGNAL_REGIME_BLOCKED"
SIGNAL_SPREAD_ABNORMAL = "SIGNAL_SPREAD_ABNORMAL"
SIGNAL_INSUFFICIENT_EVIDENCE = "SIGNAL_INSUFFICIENT_EVIDENCE"
SIGNAL_LEVEL_NOT_RECLAIMED = "SIGNAL_LEVEL_NOT_RECLAIMED"
SIGNAL_TARGET_INSUFFICIENT_R = "SIGNAL_TARGET_INSUFFICIENT_R"

# ── Risk rejections ───────────────────────────────────────────────────────────
RISK_DAILY_LOSS_STOP = "RISK_DAILY_LOSS_STOP"
RISK_DRAWDOWN_LIMIT = "RISK_DRAWDOWN_LIMIT"
RISK_MAX_POSITIONS = "RISK_MAX_POSITIONS"
RISK_PORTFOLIO_HEAT = "RISK_PORTFOLIO_HEAT"
RISK_CORRELATED_EXPOSURE = "RISK_CORRELATED_EXPOSURE"
RISK_STOP_INVALID = "RISK_STOP_INVALID"
RISK_STOP_ABOVE_ENTRY = "RISK_STOP_ABOVE_ENTRY"
RISK_ZERO_STOP_DISTANCE = "RISK_ZERO_STOP_DISTANCE"
RISK_RR_TOO_LOW = "RISK_RR_TOO_LOW"
RISK_LEVERAGE_EXCEEDED = "RISK_LEVERAGE_EXCEEDED"
RISK_SPREAD_TOO_WIDE = "RISK_SPREAD_TOO_WIDE"
RISK_EDGE_BELOW_FEES = "RISK_EDGE_BELOW_FEES"
RISK_EVENT_WINDOW = "RISK_EVENT_WINDOW"
RISK_EXCHANGE_UNHEALTHY = "RISK_EXCHANGE_UNHEALTHY"
RISK_RESEARCH_HARD_BLOCK = "RISK_RESEARCH_HARD_BLOCK"
RISK_MIN_NOTIONAL_BREACH = "RISK_MIN_NOTIONAL_BREACH"
RISK_CIRCUIT_BREAKER_ACTIVE = "RISK_CIRCUIT_BREAKER_ACTIVE"
RISK_FUNDING_OI_STALE = "RISK_FUNDING_OI_STALE"

# ── Execution errors ──────────────────────────────────────────────────────────
EXEC_ORDER_REJECTED = "EXEC_ORDER_REJECTED"
EXEC_STOP_PLACEMENT_FAILED = "EXEC_STOP_PLACEMENT_FAILED"
EXEC_PRECISION_ERROR = "EXEC_PRECISION_ERROR"
EXEC_DUPLICATE_ORDER = "EXEC_DUPLICATE_ORDER"
EXEC_PARTIAL_FILL = "EXEC_PARTIAL_FILL"
EXEC_CANCEL_FAILED = "EXEC_CANCEL_FAILED"
EXEC_RECONCILIATION_MISMATCH = "EXEC_RECONCILIATION_MISMATCH"
EXEC_API_TIMEOUT = "EXEC_API_TIMEOUT"
EXEC_RATE_LIMIT = "EXEC_RATE_LIMIT"
EXEC_UNPROTECTED_POSITION = "EXEC_UNPROTECTED_POSITION"

# ── Research agent ────────────────────────────────────────────────────────────
RESEARCH_STALE = "RESEARCH_STALE"
RESEARCH_MALFORMED = "RESEARCH_MALFORMED"
RESEARCH_NO_SOURCES = "RESEARCH_NO_SOURCES"
RESEARCH_EXCHANGE_INSOLVENCY = "RESEARCH_EXCHANGE_INSOLVENCY"
RESEARCH_WITHDRAWALS_FROZEN = "RESEARCH_WITHDRAWALS_FROZEN"
RESEARCH_STABLECOIN_DEPEG = "RESEARCH_STABLECOIN_DEPEG"
RESEARCH_EXCHANGE_HACK = "RESEARCH_EXCHANGE_HACK"

# ── Circuit breakers ──────────────────────────────────────────────────────────
CB_CONSECUTIVE_LOSSES = "CB_CONSECUTIVE_LOSSES"
CB_DRAWDOWN_FROM_PEAK = "CB_DRAWDOWN_FROM_PEAK"
CB_STOP_NOT_CONFIRMED = "CB_STOP_NOT_CONFIRMED"
CB_PRIVATE_API_ERRORS = "CB_PRIVATE_API_ERRORS"
CB_STRUCTURAL_CRYPTO_RISK = "CB_STRUCTURAL_CRYPTO_RISK"
